### ISSUE TITLE
Passing multiple options

### ISSUE THREAD

**Issue by amirotin** [guessit-io/guessit-rest#1]
Hi. I'm trying to pass two options into guessit rest api.
For example i use "type=movie" and "expected-title='some movie name'". As i understand sources - i must put both options into single url param:
```  ?filename=test.avi&options="type=movie expected-title=movie_name" ```

But guessit-rest doesn't parse options correctly. Instead of two separate values i get single (i.e type = [movie expected-title=movie_name])

I tryed multiple variants of option writing: with|without --, quotes, doublequotes, comas and etc.

What is correct value for multiple options?

**Comment by Toilal** [comment]
Options can be passed like with command line args, so use `"--type movie --expected-title movie_name"`

**Comment by amirotin** [comment]
It doesn't work.
i passed `options="--type movie --expected-title back to the future iii"`
and here is options i get in guessit
```
{  
   'show_property':None,
   'allowed_languages':None,
   'expected_group':None,
   'name_only':False,
   'verbose':False,
   'allowed_countries':None,
   'date_day_first':None,
   'input_file':False,
   'episode_prefer_number':False,
   'date_year_first':None,
   'filename':[  
      '--type movie --expected-title back to the future iii'
   ],
   'yaml':False,
   'json':False,
   'version':False,
   'values':False,
   'type':None,
   'properties':False,
   'advanced':False,
   'expected_title':None
}
```

full query is
`http://localhost:5000/guessit/?filename=Back To The Future Part III [1080p x264 DTS 6ch].mp4&options="--type movie -expected-title back to the future iii"`

**Comment by Toilal** [comment]
[http://v2.api.guessit.io/?filename=Back%20To%20The%20Future%20Part%20III%20[1080p%20x264%20DTS%206ch].mp4&options=%22--type%20movie%20-expected-title%20back%20to%20the%20future%20iii%22](http://v2.api.guessit.io/?filename=Back%20To%20The%20Future%20Part%20III%20[1080p%20x264%20DTS%206ch].mp4&options=%22--type%20movie%20-expected-title%20back%20to%20the%20future%20iii%22)

You have to urlencode your query string I think ... Seems to work then.

**Comment by amirotin** [comment]
Nope. Doesn't help :( I think problem is with options parse, shlex in code doesn't split the string.

When i pass `--type movie --expected-title back to the future part iii` in console i get title 'Back To The Future Part III' and from web request title is still 'Back To The Future'.

**Comment by Toilal** [comment]
I see... Do you use guessit 2.x from command line ?

**Comment by amirotin** [comment]
Yes. Both guessit and guessit-rest installed from pip

**Comment by Toilal** [comment]
Did you use `--pre` flag for guessit ? If not, you are still on 1.x branch at the moment. Please type `guessit --version` to make sure about your command line version.

**Comment by amirotin** [comment]
It's 2.0rc4

**Comment by Toilal** [comment]
Thanks ! I'll try to have a look at home later ...

**Comment by Toilal** [comment]
But in the command line input, you have to surround the expected title with quotes, 

```
$ guessit --type movie --expected-title "back to the future part iii"
```

There's probably something weird with escaping properly the parameter on the rest API.

**Comment by amirotin** [comment]
Thx for help

**Comment by amirotin** [comment]
With this combination `options="--type=movie%20--expected-title=back%20to%20the%20future%203"`
I get whole options string in type param

**Comment by amirotin** [comment]
Hi again. I found a way how to pass multiple options.
`&options=--type%3Dmovie%20--expected-title%3D%27back%20to%20the%20future%20iii%27`

but it doesn't work like in cli version. The problem is that `Back To The Future Part III [1080p x264 DTS 6ch].mkv` is parsed as `back to the future` and not `back to the future 3`. In cli version if i pass `expected-title='back to the future iii'` it works and here it doesn't help.

**Comment by Toilal** [comment]
Using [postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop), I have no problem to pass options.

`http://localhost:5000/?filename=test.avi&options=--expected-title "back to the future iii" -n`

Later in debuger ...

```json
{  
   "expected_title":[  
      "back to the future iii"
   ],
   "properties":false,
   "name_only":true,
   "episode_prefer_number":false,
   "verbose":false,
   "allowed_countries":null,
   "yaml":false,
   "version":false,
   "date_year_first":null,
   "advanced":false,
   "input_file":false,
   "type":null,
   "allowed_languages":null,
   "filename":[  

   ],
   "show_property":null,
   "date_day_first":null,
   "values":false,
   "expected_group":null,
   "json":false
}
```

If you still have issues, you can use the POST method, it may be easier ...
