### ISSUE TITLE
Force content type?

### ISSUE THREAD

**Issue by colt082295** [guessit-io/guessit-rest#3]
How can I force a content type like movie on a file? I would assume this would work, however it doesn't: "?filename=the.40.year.old.virgin.1080p.hddvd.x264-hv-sample.mkv&options=--type%3Dmovie%20"

I receive this as a result: 

`
{"title": "the", "episode": 40, "episode_title": "year old virgin", "screen_size": "1080p", "format": "HD-DVD", "video_codec": "h264", "release_group": "hv-sample", "container": "mkv", "mimetype": "video/x-matroska", "type": "movie"}
`

Using the api at http://guessit.io/, it works correctly without any options.

**Comment by r15ch13** [comment]
`http://guessit.io/guess?filename=the.40.year.old.virgin.1080p.hddvd.x264-hv-sample.mkv&type=movie`
```
{
    "container": "mkv",
    "format": "HD-DVD",
    "mimetype": "video/x-matroska",
    "releaseGroup": "hv-sample",
    "screenSize": "1080p",
    "title": "the 40 year old virgin",
    "type": "movie",
    "videoCodec": "h264"
}
```

**Comment by Toilal** [comment]
I can't reproduce, but I think something is wrong with the URL encoding of your options parameter.

[http://v2.api.guessit.io/?filename=test.S02E03.avi&options=--type%20movie](http://v2.api.guessit.io/?filename=test.S02E03.avi&options=--type%20movie)
