### ISSUE TITLE
passing multiple filenames

### ISSUE THREAD

**Issue by 2ge** [guessit-io/guessit-rest#6]
Hi,

http://v2.api.guessit.io/?filename[]=movie1.mkv&filename[]=movie2.mkv

something like that possible ? 

in returned json could be movie1.mv as key etc.

**Comment by Toilal** [comment]
I have implemented a new resource "/list/" that allow multiple filename parameters to be passed.

[http://v2.api.guessit.io/list/?filename=Game.of.Thrones.S03.1080p.BluRay.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR&filename=Duck.Dynasty.S02E07.Streik.German.DOKU.DL.WS.DVDRiP.x264-CDP&options=-a](http://v2.api.guessit.io/list/?filename=Game.of.Thrones.S03.1080p.BluRay.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR&filename=Duck.Dynasty.S02E07.Streik.German.DOKU.DL.WS.DVDRiP.x264-CDP&options=-a)

It returns a list of Match in same order as input.

You can also perform a post with json data

```json
{
   "filename":[
      "Game.of.Thrones.S03.1080p.BluRay.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR",
      "Duck.Dynasty.S02E07.Streik.German.DOKU.DL.WS.DVDRiP.x264-CDP"
   ],
   "options":"-a"
}
```
