### ISSUE TITLE
API Url

### ISSUE THREAD

**Issue by Toilal** [guessit-io/guessit-rest#9]
Hi @wackou

I think this project and guessit 2 is stable enough to host the v2 api on `api.guessit.io` instead of `v2.api.guessit.io`. The actual subdomain https://api.guessit.io/ seems to point to another project. Can you map it to my box IP 62.210.182.194 ?

Also I which you could also create a `app.guessit.io` subdomain directing to the same IP because I want to publish the guessit-webapp project too.

Thanks !

**Comment by wackou** [comment]
done! both `api.guessit.io` and `app.guessit.io` now point to 62.210.182.194.
Give it a bit of time for the DNS to propagate, and you should be all set.

Thanks for your continued work on the project!
